@echo off
echo Starting RISBOW Backend Services...

echo [1/2] Starting Docker Containers (Postgres + Redis)...
docker-compose up -d postgres redis

echo [2/2] Starting NestJS Server...
npm run start:dev
